typography_spectrum: 0.50083
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5193169408012182
  lightness: 0.3759756311774254
  saturation: 0.08569534355774522
  rhythmicContrast: 0.9795960753690451
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75703
analytics:
  google: null
  facebook: null
  twitter: null
name: DanielGreen
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Googz
    url: google.com
    type: external
favicon: null
title: Trying for the second time.
description: I hope I didn't waste $90.
purpose: []
