name: DanielGreen
favicon: null
layout_spectrum: 0.75703
typography_spectrum: 0.50083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5193169408012182
  lightness: 0.3759756311774254
  saturation: 0.08569534355774522
  rhythmicContrast: 0.9795960753690451
purpose: []
